[package]
name = "rust_sha"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
sha2 = "0.9.5"

[lib]
crate-type = ["cdylib"]
